version: "3.9"

services:

  productor-agregar-libro:
    build:
      context: ../agents/Productor-SpringBoot
    ports:
      - "8082:8080"
    environment:
      - SPRING_RABBITMQ_HOST=10.6.101.95
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=123456
    networks:
      - my_network

  productor-eliminar-libro:
    build:
      context: ../agents/Productor-FastAPI
    ports:
      - "8002:8000"
    environment:
      - RABBITMQ_URL=amqp://admin:123456@10.6.101.95:5672/
    networks:
      - my_network

  productor-actualizar-libro:
    build:
      context: ../agents/Productor-FastAPI-Update
    ports:
      - "8003:8000"
    environment:
      - RABBITMQ_URL=amqp://admin:123456@10.6.101.95:5672/
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
