version: "3.8"

services:
  consumidor-malaga:
    build:
      context: ../agents/Consumidor-SpringBoot
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-malaga:5432/biblioteca_malaga
      - SPRING_DATASOURCE_USERNAME=Solus
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=123456
    depends_on:
      - db-malaga
      - rabbitmq
    networks:
      - my_network

  consumidor-node-barbosa:
    build:
      context: ../agents/Consumidor-NodeJS
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://Solus:123456@db-barbosa:5432/biblioteca_barbosa
      - RABBITMQ_URL=amqp://admin:123456@rabbitmq:5672/
    depends_on:
      - db-barbosa
      - rabbitmq
    networks:
      - my_network

  db-barbosa:
    image: postgres:14
    environment:
      - POSTGRES_DB=biblioteca_barbosa
      - POSTGRES_USER=Solus
      - POSTGRES_PASSWORD=123456
    ports:
      - "5435:5432"
    volumes:
      - postgres-data-barbosa:/var/lib/postgresql/data
    networks:
      - my_network

  db-malaga:
    image: postgres:14
    environment:
      - POSTGRES_DB=biblioteca_malaga
      - POSTGRES_USER=Solus
      - POSTGRES_PASSWORD=123456
    ports:
      - "5433:5432"
    volumes:
      - postgres-data-malaga:/var/lib/postgresql/data
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123456
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 20s
      retries: 5
      timeout: 5s

  productor-agregar-libro:
    build:
      context: ../agents/Productor-SpringBoot
    ports:
      - "8082:8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin
      - SPRING_RABBITMQ_PASSWORD=123456
    depends_on:
      - rabbitmq
    networks:
      - my_network

  consumidor-socorro:
    build:
      context: ../agents/Consumidor-FastAPI
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://Solus:123456@db-socorro:5432/biblioteca_socorro
      - RABBITMQ_URL=amqp://admin:123456@rabbitmq:5672/
    depends_on:
      - db-socorro
      - rabbitmq
    networks:
      - my_network

  productor-eliminar-libro:
    build:
      context: ../agents/Productor-FastAPI
    ports:
      - "8002:8000"
    environment:
      - RABBITMQ_URL=amqp://admin:123456@rabbitmq:5672/
    depends_on:
      - rabbitmq
    networks:
      - my_network

  productor-actualizar-libro:
    build:
      context: ../agents/Productor-FastAPI-Update
    ports:
      - "8003:8000"
    environment:
      - RABBITMQ_URL=amqp://admin:123456@rabbitmq:5672/
    depends_on:
      - rabbitmq
    networks:
      - my_network

  db-socorro:
    image: postgres:14
    environment:
      - POSTGRES_DB=biblioteca_socorro
      - POSTGRES_USER=Solus
      - POSTGRES_PASSWORD=123456
    ports:
      - "5434:5432"
    volumes:
      - postgres-data-socorro:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  postgres-data-barbosa:
  postgres-data-malaga:
  postgres-data-socorro:

networks:
  my_network:
    driver: bridge
